-- SCA Feedback Statements (Domains 1-3), normalized structure
-- Source: https://www.rcgp.org.uk/mrcgp-exams/simulated-consultation-assessment/feedback-statements
-- `standard` and `description` contain cleaned HTML (h3/p/ul/li/strong/em/br only).

DROP TABLE IF EXISTS `sca_feedback_statements`;
DROP TABLE IF EXISTS `sca_feedback_domains`;

CREATE TABLE `sca_feedback_domains` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `standard` TEXT NOT NULL COMMENT 'Standard for marking (passing level), HTML',
  `sort_order` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sca_feedback_statements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `domain_id` TINYINT UNSIGNED NOT NULL,
  `sl_no` TINYINT UNSIGNED NOT NULL COMMENT 'Statement number within the domain (as on RCGP page)',
  `subject` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL COMMENT 'Educator notes, HTML',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_domain_statement` (`domain_id`,`sl_no`),
  CONSTRAINT `fk_sca_statement_domain` FOREIGN KEY (`domain_id`)
    REFERENCES `sca_feedback_domains` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `sca_feedback_domains` (`id`, `name`, `standard`, `sort_order`) VALUES
(1, 'Domain 1 - Data gathering and diagnosis', '<ul><li>Systematically gathers and organises relevant and targeted information to address the needs of the patient and their problem(s).</li>\n<li>Adopts a structured and informed approach to problem-solving, generating an appropriate differential diagnosis or relying on first principles where the presentation is undifferentiated, uncertain or complex.</li></ul>', 1);

INSERT INTO `sca_feedback_domains` (`id`, `name`, `standard`, `sort_order`) VALUES
(2, 'Domain 2 - Clinical management and medical complexity', '<ul><li>Demonstrates the ability to formulate safe and appropriate management options which includes effective prioritisation, time, self-management and continuity.</li>\n<li>Demonstrates commitment to providing optimum care in the short and long-term, whilst acknowledging the challenges.</li></ul>', 2);

INSERT INTO `sca_feedback_domains` (`id`, `name`, `standard`, `sort_order`) VALUES
(3, 'Domain 3 - Relating to others', '<ul><li>Demonstrates ethical awareness.</li>\n<li>Shows ability to communicate in a person-centred way.</li>\n<li>Demonstrates initiative and flexibility in using various consultation approaches in order to overcome any communication barriers and to reach a shared understanding with the patient.</li></ul>', 3);

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 1, 'Data gathering was insufficient to enable safe assessment of the condition/situation', '<h3>Explanation</h3>\n<p>Examiners felt that the history taken was insufficient in terms of breadth or depth to enable you to safely assess the condition and its severity.</p>\n<h3>Suggestions</h3>\n<p>Ensure you consider the presence or absence of relevant ‘red flags’.</p>\n<p>An exhaustive enquiry into a list of all possible symptoms is unnecessary and impractical; but ask enough to demonstrate you have considered the relevant serious possibilities.</p>\n<p>Be curious and interested in the severity of the patient’s presentation and how the symptoms are affecting them.</p>\n<p>Watch videos of your consultations, or role play scenarios with your supervisor or peer study group.</p>\n<p>Have you enough information to form a differential diagnosis and distinguish significant illness from something more minor or self-limiting? For example, if you decide a patient has mechanical back pain, have you excluded cauda equina? If they are bleeding PV, have you considered pregnancy, or if their smear is up-to-date? With each consultation consider, what else could this be? What do I need to exclude?</p>\n<p>Create short lists to prompt red flags for common presentations in GP.</p>\n<p>Watching other more experienced colleagues consult will help.</p>\n<h3>Capability areas</h3>\n<ul><li>Data gathering and interpretation.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 2, 'Existing information about the case was insufficiently utilised', '<h3>Explanation</h3>\n<p>Examiners felt that the consultation would have benefitted from reference to information provided in the case notes. Data gathering includes understanding and incorporating data from the patient record to inform the consultation.</p>\n<p>For example, if a patient has seen a doctor previously, refer to this. ‘I note you saw my colleague last week about nose bleeds and she made some suggestions. How have you been since then?’ Or ‘Our notes say you are taking metformin, atorvastatin and ramipril, is that correct?’ Rather than, ‘are you taking any medication?’</p>\n<p>You might notice a patient has an allergy or has previously tried a medication. Perhaps their smear is due. They may have suffered a recent bereavement. Consider if this might be relevant or referred to in your consultation.</p>\n<p>A low MCV might indicate iron deficiency anaemia, so a change in bowel habit may need more urgent investigation than a normal Hb might suggest. A change in eGFR may mean that medications such as metformin need their dose adjusting.</p>\n<h3>Suggestions</h3>\n<p>Take time before starting a consultation in your surgery. What information is helpful for you to know? What is the patient’s past medical history? What medications are they taking? How recently have they been seen and for what reason? Are there any ongoing health issues that should be raised?</p>\n<p>Notice how familiarity with the patient record informs the consultation, compared to seeing someone ‘blind’ with no record, for example, in an Urgent Unscheduled Care or A&amp;E setting.</p>\n<p>Plan a tutorial on record keeping and the function(s) of GP notes.</p>\n<h3>Capability areas</h3>\n<ul><li>Data gathering and interpretation.</li>\n<li>Organisation, management and leadership.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 3, 'Relevant psychological or social information insufficiently recognised or responded to', '<h3>Explanation</h3>\n<p>Examiners felt that you needed to explore the patient’s social or psychological situation further, to establish context. Or that this contextual information was not sufficiently conveyed in your discussion or decision-making. Often patients present with a physical problem, but its effect may be provoked, magnified or complicated by their social or psychological situation.</p>\n<p>This is about seeing and valuing the whole person, rather than simply their symptom. Recognising that no two patients’ experience of an illness are the same.</p>\n<p>For example, a diagnosis of “tennis elbow / lateral epicondylitis” might appear to be relatively straightforward. However, if the patient is self-employed, currently out of work with a newly pregnant partner, suggesting a Fit Note or time away from the factors exacerbating the elbow pain might be unhelpful. A different approach to a cough or rash will be needed for someone about to take a flight to start a gap year abroad, from someone who is street homeless or someone who is a current star of musical theatre. Without establishing the psycho-social context, it is harder to produce a management plan that is appropriate and acceptable to the individual patient.</p>\n<h3>Suggestions</h3>\n<p>Be curious about your patients and their experiences. Establish the impact of an illness on their lives. Recognise and value their needs and priorities. This is not a tick box exercise, but a demonstration of wishing to understand how to make this consultation relevant, responsive and unique for the individual concerned.</p>\n<p>Ask for feedback from your supervisor on this aspect of your consulting; role play cases you have encountered with your peers, with you ‘role reversing’ by playing the part of the patient.</p>\n<p>Practice being curious about the person, their social or psychological situation and how this might affect their experience of symptoms, or their preferences for management/next steps.</p>\n<h3>Capability areas</h3>\n<ul><li>Practicing holistically, promoting health and safeguarding.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 4, 'Data gathering was unsystematic and/or disorganised', '<h3>Explanation</h3>\n<p>Examiners did not feel that the consultation had a logical structure.</p>\n<p>Consultations are not scripted or linear, it is often necessary to return to aspects of data gathering or test new hypotheses as information comes to light. The consultation is a conversation between two people and as such, may be unpredictable.</p>\n<p>However, your data gathering may have appeared disjointed, your questioning failing to show a reasoned way of thinking. The consultation may have appeared disorganised or even chaotic, with some elements apparently occurring at random. This gives the impression of a doctor who may miss important clinical issues because he/she is not systematic; or one who is at a loss for what to ask.</p>\n<p>For example, for a patient with long COVID, a systematic approach to their symptoms, rather than a ‘scattergun’ enquiry of irrelevant, disjointed questions may be more helpful both diagnostically and therapeutically. It may seem topsy-turvy or presumptuous to give a diagnosis before data has been gathered. Or to agree to a prescription prior to establishing safety.</p>\n<p>Aim for a stepwise approach to systematically gather information, focus your enquiry and target questions to the problem.</p>\n<h3>Suggestions</h3>\n<p>Consider the various GP consultation models (such as Neighbour, Pendleton or Cambridge-Calgary). Ask a colleague or your supervisor to critique the structure or organisation of your consulting.</p>\n<p>Using open questions to explore the presenting features, before focussing on specific detail with closed questions, is often helpful.</p>\n<p>Try signposting, where you signal to the patient what you are about to do. For example, ‘I would like to ask you some questions about your health in the past.’ If you should need to return to aspects of data gathering later in the consultation, consider saying, ‘I realise I need to return to some other questions now…’</p>\n<p>Summarising also demonstrates that you are collating and processing the collected information; and is useful in allowing the patient to clarify anything misunderstood.</p>\n<h3>Capability area</h3>\n<ul><li>Data gathering and interpretation.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 5, 'Ineffective approach or prioritisation in data gathering, when presented with multiple or complex problems', '<h3>Explanation</h3>\n<p>The examiner felt you were insufficiently able to generate functional solutions for data gathering when the presentation was complex or multifactorial.</p>\n<p>This may be about prioritisation; recognising the most pressing or important issues for this encounter and negotiating this with the patient. For example, if a patient has hay fever, longstanding headaches and bleeding on passing stool we might agree to focus on the latter today, offering time for the other issues in future.</p>\n<p>Or this may be about seeing the bigger picture, rather than attempting an exhaustive evaluation of each of the symptoms in turn. For example, if a patient has symptoms in multiple bodily systems, might there be a unifying diagnosis? Or might exploring why all this is happening at once and what the patient is most worried about be more helpful than an exhaustive enquiry into each and every symptom, as long as this is safe?</p>\n<h3>Suggestion</h3>\n<p>Ensure you see plenty of complex patients, including those with co-morbidity. This may need triaging as new practice members often have more ‘book on the day’ single-issue consultations; complex patients may have a ‘usual doctor’ already. Discuss cases with your supervisor, as CBDs. Consider tutorials or peer study group sessions on complexity and negotiating priorities with patients.</p>\n<h3>Capability area</h3>\n<ul><li>Managing medical complexity.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 6, 'The implications of relevant findings identified during the data gathering were insufficiently recognised or understood', '<h3>Explanation</h3>\n<p>Examiners felt that you did not demonstrate an ability to identify or recognise significant findings in the consultation. Some findings may have been identified but not acted upon appropriately, so that examiners conclude you did not recognise their significance. This skill requires you to correctly recognise and respond to the significance of information in the consultation. The abnormal findings will often relate to common or important conditions.</p>\n<p>A patient who you find to be cognitively impaired may not be able to follow complex management instructions without additional support. Or perhaps a patient experiencing unilateral headache was diagnosed as migraine rather than temporal arteritis, despite tenderness on brushing their hair.</p>\n<p>A newly confused patient who takes DOACs may need an urgent CT head to exclude a subdural.</p>\n<h3>Suggestions</h3>\n<p>Consider how you pick up on abnormal findings and respond safely and appropriately. Discuss your consultations with colleagues, asking them to comment, particularly on your response to abnormal findings that emerge in the consultation.</p>\n<h3>Capability areas</h3>\n<ul><li>Data gathering and interpretation.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 7, 'Differential diagnoses or hypotheses were inadequately generated or tested', '<h3>Explanation</h3>\n<p>Examiners felt that you did not consider relevant conditions in the differential diagnosis. Perhaps you should have considered and explored a broader range of possibilities, before narrowing your diagnosis. Or perhaps the examiners felt it was impossible or unnecessary to make a single diagnosis during the consultation and that different options should be explored further.</p>\n<p>For example, although the patient may appear anxious, before concluding she has anxiety disorder, might it be helpful to consider ADHD, might she use cocaine, or might she have issues with her thyroid gland?</p>\n<h3>Suggestions</h3>\n<p>Try to consider and test a range of possible diagnoses. Avoid assumptions about patients. Notice if you employ confirmation bias, where you favour new information that confirms previous beliefs, disregarding other evidence that may not align.</p>\n<p>Sharing insight into your diagnostic reasoning with the patient (and thereby the examiner) is helpful too. For example, ‘I had thought about X but as your Y is not painful this is less likely, however if Z happens, we will need to reconsider this next time.’</p>\n<h3>Capability area</h3>\n<ul><li>Making diagnosis/decisions.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(1, 8, 'Decision-making or diagnosis was illogical, incorrect or incomplete', '<h3>Explanation</h3>\n<p>Examiners felt that you failed to make the appropriate diagnosis and/or that the reasoning behind your conclusions did not make sense, clinically.</p>\n<p>Making a diagnosis or reaching a decision means making a conclusion about what is likely, from the information you have available to you.</p>\n<p>For example, did you conclude someone had psoriasis when the rash and history were those of a fungal skin infection? Did you decide someone has restless legs, despite them being vegan and have a very low B12? Could that URTI more likely be hay fever, based on the information available. Perhaps the ECG provided showed Atrial Fibrillation but you did not diagnose this.</p>\n<p>Or did you appear to sit on the fence and avoid communicating a diagnosis that seemed obvious, for fear of getting it wrong in the examination?</p>\n<h3>Suggestions</h3>\n<p>Try to reach a decision before debriefing a patient with your supervisor and ensure you challenge yourself about the likely diagnosis. Is your decision-making in line with that of your colleagues?</p>\n<p>Do you tend to be dogmatic or quick to jump to conclusions in your diagnoses?</p>\n<p>Is there an area of the curriculum you are less confident in?</p>\n<p>Consider proactively addressing this in your reading, your patient experience and your other learning opportunities.</p>\n<p>Random case analyses and case-based discussions are also very helpful in putting your decision-making in the spotlight.</p>\n<h3>Capability areas</h3>\n<ul><li>Making diagnosis/decisions.</li>\n<li>Clinical Management.</li>\n<li>Managing medical complexity.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 1, 'The management plan relating to referral was inappropriate or not reflective of current practice', '<h3>Explanation</h3>\n<p>You are expected to show that your clinical management skills are in line with current UK best practice. You may not have developed a plan at all, where a referral was needed. Or you may have referred to an inappropriate place. Or you may have referred when this was not necessary/appropriate in this case.</p>\n<p>You are expected to understand and value the role of the multi-disciplinary team. In addition to secondary care, the referral in question may be to counselling, community or social services. It may also be about encouraging/signposting self-referral.</p>\n<p>For example, a referral to a rheumatologist for gout may be unnecessary. Or a two-week wait, rather than routine referral for unexplained PR bleeding in a 54-year-old could have been more suitable.</p>\n<h3>Suggestions</h3>\n<p>Your management plan should be coherent and feasible. You should be familiar with current national guidelines such as those published by NICE (National Institute of Clinical Excellence) and SIGN (Scottish Intercollegiate Guidelines Network).</p>\n<p>Use the concept of PUNs (Patients’ Unmet Needs) and DENs (Doctors’ Educational Needs) to improve management. This means learning on the job from dilemmas and challenges as they arise, case by case: Make a habit of referring to guidelines after you have seen each patient at work. Notice areas in the MRCGP (curriculum clinical topic guides) that you need more experience with. Plan tutorials or peer learning to support these areas, or use your self-directed learning sessions to attend specialist clinics.</p>\n<h3>Capability area</h3>\n<ul><li>Clinical Management.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 2, 'The management plan relating to prescribing of medication was inappropriate or not reflective of current practice', '<h3>Explanation</h3>\n<p>You are expected to show that your clinical management skills are in line with current UK best practice, making safe prescribing decisions, considering relevant drug interactions, dosing, and side effects. You may not have developed a plan at all, where a prescription was needed. You may have prescribed or failed to stop an inappropriate medication; or issued an incorrect dose. Or you may have prescribed when no prescription was necessary in this case.</p>\n<p>This may also refer to the suggestion of over the counter (non-prescription) medication. For example, perhaps tamsulosin rather than finasteride would have been more suitable for a gentleman with LUTS, first line. Or when prescribing alendronic acid, advice about side effects and how to take should have been given, enhancing patient safety.</p>\n<h3>Suggestions</h3>\n<p>Your management plan should be coherent and feasible. You should be familiar with current national guidelines such as those published by NICE (National Institute of Clinical Excellence) and SIGN (Scottish Intercollegiate Guidelines Network).</p>\n<p>Make a habit of referring to prescribing guidelines and/or the BNF after you have seen each patient at work. Where appropriate, consider other options before prescribing and be aware of the risks of polypharmacy and the need to deprescribe, too.</p>\n<p>Get involved with the work of repeat prescribing in your surgery, complete your Prescribing Assessment for WPBA. Attend prescribing meetings at work with your team and community pharmacist.</p>\n<h3>Capability area</h3>\n<ul><li>Clinical Management</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 3, 'The management plan relating to investigations was inappropriate or not reflective of current practice', '<h3>Explanation</h3>\n<p>You are expected to show that your clinical management skills are in line with current UK best practice. You may not have suggested investigations at all, where they were needed. You may have suggested inappropriate or unjustifiable investigations. Or you may have arranged investigations when none were needed in this case.</p>\n<p>For example, it may not be necessary to request an MRI scan for simple back pain, or a sputum sample for an URTI. If someone has symptoms of irritable bowel syndrome it may be unclear why a vitamin D level is suggested. Alternatively, after a cough worsening over several weeks, it may have been advisable to request a chest Xray.</p>\n<h3>Suggestions</h3>\n<p>Your management plan should be coherent and feasible. You should be familiar with current national guidelines such as those published by NICE (National Institute of Clinical Excellence) and SIGN (Scottish Intercollegiate Guidelines Network).</p>\n<p>Investigations requested should be targeted and relevant, answering a specific clinical question. It should be clear why they are being chosen, based on the probability of disease and with an awareness of budgetary governance.</p>\n<p>You may feel that it would be better to be ‘on the safe side’ by ordering a battery of tests and whilst understandable, this can make you appear indiscriminate.</p>\n<p>Collect a list of all the investigations you have requested over a few sessions at work. Compare with others, peers or your supervisor. What was the reason for choosing those investigations? Were they helpful and/or justified? Plan a tutorial where you share and action your supervisor’s results list and vice versa.</p>\n<h3>Capability area</h3>\n<ul><li>Clinical Management.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 4, 'The management plan relating to prevention, health promotion or rehabilitation was inadequate or inappropriate', '<h3>Explanation</h3>\n<p>You are expected to encourage prevention of illness, offer health promotion and rehabilitation strategies, where needed. These may include issuing a sick note, encouraging patient autonomy and self-care, prioritising ‘lifestyle’ advice. Sometimes this might include recognising the ‘gatekeeper’ role of the GP in prioritising NHS resources and/or reducing dependency on healthcare.</p>\n<p>For example, a patient with COPD would benefit from pulmonary rehabilitation, smoking cessation and flu vaccination. Did you focus mainly on which inhaler to provide?</p>\n<p>Another patient may need a sick note due to their psoriasis flare. Did you refuse this unnecessarily? Or grant one that may be unhelpfully long in duration, when self-certification may be a good first step?</p>\n<p>Someone with threadworms might be gently signposted to the pharmacist for simple over the counter medications in future, assuming they can afford this.</p>\n<h3>Suggestion</h3>\n<p>Consider whether there are important areas of prevention, health promotion or rehabilitation you might encourage. For example, do you know some simple exercises for mild knee pain? Or understand how to support someone locally with smoking cessation or weight loss? Are you aware of NHS screening programs? How do you respond to requests for housing letters or fit notes?</p>\n<p>Think about the different types of NHS resource that GPs are ‘gatekeepers’ for, and how reference to these emerge in our consultations. This does not mean that you are expected to refuse access to services, new medications or ‘fit notes’, but that you show your awareness of the issues and responsible use of resources.</p>\n<h3>Capability area</h3>\n<ul><li>Practicing holistically, promoting health and safeguarding.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 5, 'The plan relating to the medical management of risk was inadequate or inappropriate', '<h3>Explanation</h3>\n<p>Medical management of risk means ‘the forecasting and evaluation of risks together with identification of procedures to avoid or minimise their impact’. Risk management prioritises patient safety and ensures an appropriate response to preventing risk or managing error.</p>\n<p>Examiners did not feel that you managed risk appropriately. This could mean either that you failed to identify the potential risks or that having done so you did not respond in an appropriate way. Perhaps you didn\'t seem aware of the responsibility for a systems\' response, for example significant event analysis or the complaints process.</p>\n<p>Alternatively, you may have been too risk-averse in an otherwise safe encounter.</p>\n<p>For example, was the risk of a patient falling, or the impact on their eGFR, greater than the risk of their slightly raised blood pressure? Should those risks have been prioritised before following a BP guideline?</p>\n<p>Was the risk of overdose greater than the convenience of issuing three months’ of medication?</p>\n<p>Did a temporary patient with no records receive care without reference to his registered GP in a way that created risk?</p>\n<p>Did a concerned daughter who identified a problem with her cognitively impaired father’s care fail to receive supportive signposting to the complaints procedure and a willingness to investigate via a significant event analysis with the team?</p>\n<p>Were documents shared without consideration of data protection?</p>\n<h3>Suggestions</h3>\n<p>Be aware of NHS guidelines around medical risk management. Engage in partners’ meetings and significant event / complaints analyses in the practice to become familiar with the practical applications of risk management in the workplace. Discuss risk with your supervisor and consider risk management as a priority in your patient encounters.</p>\n<h3>Capability areas</h3>\n<ul><li>Clinical Management.</li>\n<li>Organisation management and leadership.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 6, 'The implications of co-morbidity were insufficiently considered', '<h3>Explanation</h3>\n<p>You are expected to recognise the inevitable conflicts that arise when managing patients with multiple problems and takes steps to adjust care appropriately.</p>\n<p>It is also important to simultaneously manage the patient’s health problems, both acute and chronic.</p>\n<p>For example, although a guideline for managing one chronic disease may indicate best practice for prescribing for that single condition, sometimes the other conditions a patient is living with may mean it is necessary to alter or even avoid prescribing. This may be particularly true for frail older adults and in the case of polypharmacy.</p>\n<p>Or a patient with hands affected by rheumatoid arthritis, who has CKD may not be able to open bottles of ibuprofen during a flare, nor be safe to take them, given their eGFR.</p>\n<h3>Suggestion</h3>\n<p>Ensure you regularly consult with people experiencing multiple illnesses or chronic disease. This may mean pro-actively triaging your cases or taking over the care of frail vulnerable adults. Participate in team meetings for example where housebound patients are discussed with district/palliative nurses. Use self-directed learning time to attend community falls clinics, or care of the older adult outpatients. Be aware of the literature surrounding over-medicalisation and the downsides of polypharmacy.</p>\n<h3>Capability areas</h3>\n<ul><li>Managing medical complexity</li>\n<li>Making diagnosis/decisions</li>\n<li>Maintaining an ethical approach</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 7, 'Uncertainty, including that experienced by the patient, was managed ineffectively', '<h3>Explanation</h3>\n<p>Examiners felt that clinical uncertainty and/or that experienced by the patient was ineffectively managed.</p>\n<p>It may be that time as a diagnostic aid was not used appropriately. Or that you were unable to tolerate or ‘hold’ uncertainty effectively. Or that management strategies used to respond to the patient’s uncertainty were not helpful.</p>\n<p>For example: Another scan may not be helpful for a patient with medically unexplained symptoms. It might be reasonable to wait a week or so before prescribing for, or investigating a symptom that is likely to be self-limiting. On the other hand, someone who declines antenatal testing for Down Syndrome may need additional support and information while she completes her pregnancy.</p>\n<h3>Suggestion</h3>\n<p>Be aware of the literature surrounding over-medicalisation. Plan a tutorial or peer study group session on uncertainty in General Practice. Consider how uncertainty might be safely tolerated or responded to.</p>\n<h3>Capability area</h3>\n<ul><li>Managing medical complexity.</li>\n<li>Practising holistically, promoting health and safeguarding.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 8, 'Inappropriate or inadequate arrangements for follow-up, continuity and/or safety netting', '<h3>Explanation</h3>\n<p>Examiners felt that your follow-up arrangements were not adequate or that you did not ensure that there was an appropriate safety net.</p>\n<p>Making arrangements for follow-up demonstrates your commitment to the continuity of care of patients. It shows that you are prepared to take responsibility for managing the ongoing presentation of the condition until the problem has been resolved. However, inappropriate or unrealistic follow-up is unhelpful both for the index patient and for other patients who may be unable to access their GP, with limited appointment availability.</p>\n<p>Safety-netting describes the information you should be giving to each patient about what to expect, including a time scale if appropriate, and what to do if symptoms get worse or develop in some unexpected way. However, safety-netting may cause unnecessary alarm if performed without care.</p>\n<p>For example, having diagnosed upper abdominal pain as simple indigestion, consider how a safety net that suggests going to A&amp;E if it recurs ‘in case it is your heart’ might be received.</p>\n<h3>Suggestion</h3>\n<p>Consider how you end your consultations. Is it always with a safety net and if so, is that appropriately tailored to the consultation? Be aware of the literature surrounding the benefits of continuity of care in GP and discuss the systems that enable this in your practice, with the team. Notice if you are booking a follow-up and consider if this is necessary or practical.</p>\n<h3>Capability area</h3>\n<ul><li>Clinical Management.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(2, 9, 'Time management in the consultation was ineffective', '<h3>Explanation</h3>\n<p>Examiners felt that you showed poor time management during the cases, perhaps taking too long over certain tasks or failing to cover what was thought to be essential as time ran out.</p>\n<p>The ability to consult within a short time is essential for current practice. We must manage time as a resource for the sake of ourselves, our other patients and the whole team.</p>\n<p>A common reason for running out of time in cases is taking too long over data gathering, and then having to rush clinical management, explanations and follow-up arrangements. Pace yourself and consider roughly how long you should be taking for the different parts of the consultation. Remember the SCA cases are designed to be possible in the twelve-minute time frame.</p>\n<p>A reminder: Data gathering requires us to be appropriately selective in the questions we ask, tailored to the circumstances of the patient, rather than being an ‘all inclusive’ review of systems.</p>\n<h3>Suggestions</h3>\n<p>Try to see patients within a limited time frame at work. Set up a clock within eyeshot of your desk. Role play strategies for managing time, especially in challenging situations. Observe clinicians who consult effectively but efficiently and incorporate their techniques into your practice.</p>\n<h3>Capability areas</h3>\n<ul><li>Clinical management.</li>\n<li>Managing medical complexity.</li>\n<li>Communication and consultation skills.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 1, 'Communication skills, including the non-verbal, responding to cues and/or active listening were insufficiently demonstrated', '<h3>Explanation</h3>\n<p>The examiner felt you did not demonstrate sufficient communication skills for independent practice. This may include responding to cues that could have enhanced your understanding. They may have felt your listening skills were poor, for example you may have asked questions, but not listened to or responded to the answers. Or that your consulting was ‘formulaic’, meaning it felt rigid or even scripted: Perhaps you used phrases that did not seem relevant or helpful to the person, or did not appear to acknowledge their reply appropriately.</p>\n<p>For example, if you repeat a stock phrase such as ‘I am sorry to hear that’ too frequently it loses its impact. Perhaps when a patient says ‘I am not sociable these days’ you should have been curious as to what that means, or why. Perhaps when a patient tells you they are worried about a breast lump there is a better response than ‘OK, is there anything else you’d like to discuss today?’</p>\n<h3>Suggestions</h3>\n<p>Active listening includes paying attention and responding appropriately. It is essential for building a relationship of trust with the patient. It is helped by clarifying and summarising what has been shared to demonstrate understanding.</p>\n<p>Cues can include non-verbal gestures, pauses in speech or facial expressions. Cues are moments in the patient’s account that indicate there are additional areas to explore.</p>\n<p>To avoid ‘formulaic’ consulting, try to avoid rigidly applying a set consulting ‘model’ to the consultation that does not respond to the individual patient.</p>\n<p>Watch videos of your consultations, seeking feedback from your supervisor. Notice how you demonstrate you are listening, how you facilitate the consultation and the timing of your interruptions.</p>\n<p>Practice different phrases to respond authentically to the patient’s contribution. Watch your colleagues consult and write down every possible cue you notice.</p>\n<h3>Capability area</h3>\n<ul><li>Communication and consultation skills.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 2, 'The person’s agenda, health beliefs and/or preferences were insufficiently explored', '<h3>Explanation</h3>\n<p>The examiners felt the consultation was insufficiently person-centred.</p>\n<p>It is important to understand the context of the illness; and attach importance to the subjective aspects of medicine. This means always seeing the patient as a unique person and being curious; then valuing patient preferences and expectations.</p>\n<p>For example, a patient whose neighbour has lung cancer may have fears about their own cough. Another patient may be vaccine hesitant due to health beliefs which are understandable and strongly held in their community.</p>\n<h3>Suggestion</h3>\n<p>Ensure you explore the person\'s ideas, concerns and expectations; also consider the impact the situation has had on their life.</p>\n<h3>Capability areas</h3>\n<ul><li>Communication and consultation skills.</li>\n<li>Practising holistically, promoting health and safeguarding.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 3, 'The circumstances, relevant cultural differences and/or preferences of those involved were insufficiently responded to', '<h3>Explanation</h3>\n<p>Examiners felt that you might not have made full use of the information given by the patient to you during the consultation. You may not have sufficiently demonstrated the ability to work in partnership with your patient to develop a shared management plan. It is important to take account of the patient’s agenda, health beliefs or preferences in the development of a management plan.</p>\n<p>For example, a coughing patient whose neighbour has lung cancer may need particular reassurance or investigation to assuage their fear. Another patient who is vaccine hesitant due to health beliefs which are understandable and strongly held in their community might be receptive to signposting of resources produced by community leaders and a non-pressurising approach.</p>\n<p>Patient-centred doctors are responsive to patient preferences about their health. This does not mean you can/should always be patient led. But the information about their unique situation and preferences should inform how you proceed and what you do next.</p>\n<h3>Suggestions</h3>\n<p>Practice responding appropriately to your patients’ agenda and preferences, incorporating these where possible into your plans and explanations. Try to involve patients in making decisions wherever possible.</p>\n<p>There are many educational resources about consulting skills (both in print and online) that will help.</p>\n<h3>Capability area</h3>\n<ul><li>Communication and consultation skills.</li>\n<li>Practising holistically, promoting health and safeguarding.</li>\n<li>Community orientation.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 4, 'Explanations were inadequately shared or adapted for the person’s needs', '<h3>Explanation</h3>\n<p>The examiner felt that your explanations were unclear or insufficient for patient understanding.</p>\n<p>Explanations should be relevant and understandable to patients and carers, using clear language that is both appropriate and accessible. People living with disability may need special consideration.</p>\n<p>For example, ‘There is a small lesion on your film’ contains jargon that may have little meaning to your patient. Or ‘You have some proteins causing joint pain as your body is fighting itself’ may not be useful to a Rheumatology Nurse Specialist. A hearing-impaired person may benefit from visual aids or written explanations. A child of eleven may need an adaptation of the explanation given to their adult carer/parent.</p>\n<h3>Suggestion</h3>\n<p>Try to employ communication techniques and materials that may adapt explanations to the needs of the person and/or carer.</p>\n<p>Consider what do they need to know, and how can I explain it in a way that is accessible and helpful for them? Then how might I check they understand?</p>\n<h3>Capability area</h3>\n<ul><li>Communication and consultation skills.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 5, 'A judgemental approach was shown to the person', '<h3>Explanation</h3>\n<p>Examiners felt that you conveyed judgement about the person and/or their behaviour/situation in your response to them during the consultation. This may have been implied.</p>\n<p>There are many ways a judgement can be expressed or perceived. For example, doctors may inadvertently ‘fat shame’ someone with obesity by implying ‘we get the body we deserve’; or comment ‘what did you expect?’ when a person becomes pregnant from unprotected sex. A person who has recently left prison may experience judgement when an unnecessary line of questioning about their crime ensues. Although reasonable challenge may be appropriate, criticism of parental decisions about vaccinations, food choices or smoking in the flat may be unhelpfully judgemental and therefore alienating.</p>\n<p>It may be that people with certain protected characteristics generate a less empathic, supportive response. For example, an undocumented migrant may be only superficially helped or even dismissed.</p>\n<h3>Suggestion</h3>\n<p>We all carry unconscious bias. Recognise which consultations may challenge your assumptions. Understand why some people may be more vulnerable, more susceptible to illness or less able to make changes that improve health. Try to consult with a diverse range of people and demonstrate empathy, compassion and partnership with them all where possible.</p>\n<h3>Capability areas</h3>\n<ul><li>Communication and consultation skills.</li>\n<li>Maintaining an ethical approach.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 6, 'Respect and/or sensitivity shown to the person was inadequate or inappropriate', '<h3>Explanation</h3>\n<p>The examiner felt that you failed to treat the patient with sufficient respect or sensitivity. This may involve a sufficient introduction, consent where needed or assurance of privacy or confidentiality. Being sensitive to the patient involves noticing distress and responding sensitively. Or approaching emotionally charged areas carefully and/or seeking permission before proceeding to explore areas that are difficult or intrusive for the patient.</p>\n<p>For consultations with children or patients with cognitive impairment, respect can be shown by engaging with the patient rather than entirely relying on their carer.</p>\n<p>Insufficient respect may include excessive familiarity with the patient, dismissive body language and/or patronising behaviour.</p>\n<h3>Suggestions</h3>\n<p>You can check that you are being respectful by sharing your consultations with experienced colleagues in the practice. Ask whether you are being sufficiently respectful/sensitive to the patient? Notice the times when sensitivity is more challenging, perhaps when you are under time pressure or for certain patient groups.</p>\n<p>Watch others consult and notice times when they are being sensitive and times when they could be more so.</p>\n<h3>Capability areas</h3>\n<ul><li>Fitness to practice.</li>\n<li>Maintaining an ethical approach.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 7, 'Ownership or responsibility for decision-making was inadequate or inappropriate', '<h3>Explanation</h3>\n<p>The examiners felt that you did not take adequate ownership or responsibility for your decision-making. It may have appeared you were overly risk-averse, or unsure how to manage a simple situation without unnecessary input from other sources.</p>\n<p>For example, this may involve suggesting you will ‘Run this past my colleagues’ or ‘Drop an email to Advice and Guidance from the specialist’ or arrange a physio opinion ‘just in case’ where it was not needed or warranted.</p>\n<p>It is clearly important, safe and good practice for GPs to share decisions, refer to literature and involve others. Nevertheless, sometimes a simple decision is robust, defensible and adequate, without need for additional input. This is partly about the gate-keeping role we hold in GP, but also the message we convey to patients (including raising anxiety or expectations) when it is reasonable and safe for the GP to be the only clinician involved, because in this situation the answer is straightforward or clear.</p>\n<h3>Suggestions</h3>\n<p>Try to make decisions before debriefing a patient with your supervisor, even if you do not implement the decision until discussed. Develop confidence in recognising when your decision-making is good enough. Watch experienced GPs and notice what a good enough GP will do, too.</p>\n<h3>Capability area</h3>\n<ul><li>Fitness to practice.</li>\n<li>Making diagnosis/decisions.</li>\n<li>Maintaining an ethical approach.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 8, 'Teamwork and/or understanding of others’ roles was insufficiently recognised or responded to', '<h3>Explanation</h3>\n<p>The examiners felt you did not demonstrate an adequate understanding or application of teamwork.</p>\n<p>This may mean you did not recognise, value or involve the various team members who work in primary care. Perhaps you did not demonstrate an understanding of the context within which different team members are working, for examples Health Visitors and their role in safeguarding. Or perhaps your communication with team members did not enhance team-work or patient care.</p>\n<p>For example, should the palliative care team be involved when cancer treatment comes to an end? Or might the physiotherapist have a role to play for shoulder pain? On the other hand, is it reasonable to ask your practice mental health practitioner to offer weekly appointments to someone with mild anxiety?</p>\n<h3>Suggestions</h3>\n<p>Attend and contribute to MDT meetings in your practice. Sit in with Allied Health Professionals in your practice or beyond. Try to develop an understanding of the context of their work, including how best to liaise and collaborate in the best interest of patient care.</p>\n<h3>Capability areas</h3>\n<ul><li>Working with Colleagues and in teams.</li></ul>');

INSERT INTO `sca_feedback_statements` (`domain_id`, `sl_no`, `subject`, `description`) VALUES
(3, 9, 'Safeguarding concerns were inadequately recognised or responded to', '<h3>Explanation</h3>\n<p>The examiner felt you did not understand and/or demonstrate principles of adult and child safeguarding. Perhaps you did not recognise or practice in a manner that sufficiently sought to reduce the risk of potential abuse, harm and neglect. Perhaps you did not take appropriate action including ensuring information is shared/referrals made appropriately.</p>\n<p>For example, if a parent is experiencing substance dependency did you consider the risk to his children? If a woman is disclosing partner abuse, did you have sensitive patient-centred suggestions for keeping safe and signposting specialist services? If a young female patient is being taken out of the country by her relatives, might the risk of FGM be important to consider in her case? If an older adult appears frail and unkempt, might a home visit, team discussion or even safeguarding referral to explore possible self-neglect be sensible?</p>\n<h3>Suggestions</h3>\n<p>Meet with your practice Safeguarding Lead and/or attend their safeguarding meetings. Ensure your Level 3 Safeguarding training is up-to-date and implemented. Have a tutorial on local safeguarding procedures and pathways.</p>\n<h3>Capability area</h3>\n<ul><li>Practicing holistically, promoting health and safeguarding.</li></ul>');

